#!/bin/bash

if [ "$SONARQUBE_POSTGRES_INIT" == 'true' ]; then
	psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
		CREATE USER $SONARQUBE_POSTGRES_USER WITH PASSWORD '$SONARQUBE_POSTGRES_PASSWORD';
		CREATE DATABASE $SONARQUBE_POSTGRES_DB;
		GRANT ALL PRIVILEGES ON DATABASE $SONARQUBE_POSTGRES_DB TO $SONARQUBE_POSTGRES_USER;
		ALTER ROLE $SONARQUBE_POSTGRES_USER CREATEROLE SUPERUSER;
	EOSQL
	echo
fi
